const API="/api",messages=document.querySelector("#messages"),events=document.querySelector("#events"),form=document.querySelector("#composer"),input=document.querySelector("#prompt"),send=document.querySelector("#send"),status=document.querySelector("#status"),modelSelect=document.querySelector("#model-select"),settingsDialog=document.querySelector("#settings-dialog"),settingsForm=document.querySelector("#settings-form"),modelsInput=document.querySelector("#models"),defaultModel=document.querySelector("#default-model");
function escapeHtml(value){const node=document.createElement("div");node.textContent=value;return node.innerHTML}
function fillModels(select,models,selected){select.innerHTML=models.map(model=>`<option value="${escapeHtml(model)}">${escapeHtml(model)}</option>`).join("");select.value=selected||models[0]}
async function loadSettings(){const response=await fetch(`${API}/settings`),settings=await response.json();fillModels(modelSelect,settings.models,settings.defaultModel);document.querySelector("#base-url").value=settings.baseUrl;modelsInput.value=settings.models.join("\n");fillModels(defaultModel,settings.models,settings.defaultModel);document.querySelector("#key-status").textContent=settings.hasApiKey?"✓ 已配置 API Key":"尚未配置 API Key"}
async function connect(retries=30){try{const response=await fetch(`${API}/health`);if(!response.ok)throw new Error();status.textContent="Deno Runtime 已连接 · s01 Agent Loop";await loadSettings()}catch{if(retries)setTimeout(()=>connect(retries-1),300);else status.textContent="Deno Runtime 连接失败"}}
function addMessage(kind,text){document.querySelector(".welcome")?.remove();const item=document.createElement("div");item.className=`message ${kind}`;item.textContent=text;messages.append(item);messages.scrollTop=messages.scrollHeight}
form.addEventListener("submit",async event=>{event.preventDefault();const message=input.value.trim();if(!message)return;addMessage("user",message);input.value="";send.disabled=true;status.textContent="Agent 正在思考和行动…";try{const response=await fetch(`${API}/chat`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message,model:modelSelect.value})}),data=await response.json();if(!response.ok)throw new Error(data.error||"Request failed");addMessage("agent",data.answer||"任务已完成");if(data.events?.length){events.classList.remove("hidden");events.innerHTML=data.events.map(e=>`<div class="event"><b>${e.name}</b><br>${escapeHtml(e.input)}</div>`).join("")}status.textContent="Deno Runtime 已连接 · s01 Agent Loop"}catch(error){addMessage("agent",`错误：${error.message}`);status.textContent="请求失败"}finally{send.disabled=false;input.focus()}});
document.querySelectorAll(".suggestions button").forEach(button=>button.addEventListener("click",()=>{input.value=button.textContent;input.focus()}));
document.querySelector("#settings-button").addEventListener("click",async()=>{await loadSettings();const response=await fetch(`${API}/settings/key`),data=await response.json(),keyInput=document.querySelector("#api-key"),toggle=document.querySelector("#toggle-key");keyInput.value=data.apiKey||"";keyInput.type="text";toggle.textContent="隐藏";toggle.setAttribute("aria-label","隐藏 API Key");settingsDialog.showModal()});
document.querySelector("#toggle-key").addEventListener("click",()=>{const keyInput=document.querySelector("#api-key"),toggle=document.querySelector("#toggle-key"),hidden=keyInput.type==="password";keyInput.type=hidden?"text":"password";toggle.textContent=hidden?"隐藏":"显示";toggle.setAttribute("aria-label",hidden?"隐藏 API Key":"显示 API Key")});
modelsInput.addEventListener("input",()=>{const selected=defaultModel.value,models=modelsInput.value.split("\n").map(x=>x.trim()).filter(Boolean);fillModels(defaultModel,models,models.includes(selected)?selected:models[0])});
settingsForm.addEventListener("submit",async event=>{if(event.submitter?.value==="cancel")return;event.preventDefault();const button=document.querySelector("#save-settings");button.disabled=true;try{const response=await fetch(`${API}/settings`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({apiKey:document.querySelector("#api-key").value,baseUrl:document.querySelector("#base-url").value,models:modelsInput.value.split("\n"),defaultModel:defaultModel.value})}),data=await response.json();if(!response.ok)throw new Error(data.error||"保存失败");fillModels(modelSelect,data.models,data.defaultModel);settingsDialog.close();status.textContent="模型设置已保存"}catch(error){document.querySelector("#key-status").textContent=`错误：${error.message}`}finally{button.disabled=false}});
connect();
